name: Deploy Docs

on:
  workflow_dispatch:
  push: #测试用


jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Init Job
        run: |
          mkdir raw

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Checkout Docs
        uses: actions/checkout@v4
        with:
          repository: 'MaaXYZ/MaaFramework'
          path: "raw/"
          fetch-depth: 0
          sparse-checkout: |
            docs

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Deps
        run: |
          cd src
          corepack enable
          pnpm install --frozen-lockfile

      - name: Build Docs
        run: |-
          cd src
          pnpm build
          > .vuepress/dist/.nojekyll

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist/

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          path: src/.vuepress/dist
