name: Deploy

on:
  push:
    branches: [main] # Dev
  workflow_dispatch:

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Docs
        uses: actions/checkout@v4
        with:
          repository: MaaXYZ/MaaFramework
          path: ./raw
          sparse-checkout: |
            docs

      - name: Prepare Docs
        run: |
          cd docs
          cp -r ../raw/docs/zh_cn/* docs
          cp -r ../raw/docs/en_us/* en/docs

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: yarn install

      - name: Build with VitePress
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: docs/.vitepress/dist
            publish_branch: gh-pages
